[tool.poetry]
name = "strava-viewer"
version = "0.2.0"
description = ""
authors = ["Ariel Parra <darkaico@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
dacite = "^1.6.0"
marshmallow = "^3.14.1"
python-dotenv = "^0.13.0"
flask = "^1.1.4"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-mock = "^3.6.1"
faker = "^4.18.0"
pytest-cov = "^2.12.1"
ipdb = "^0.13.9"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
